### PR TITLE
Added openapi-format as Docker

### PR DESCRIPTION
**Pull request by thim81**

### CODE REVIEW

**Comment by rngtng** [comment]
nice, is this published anywhere?

**Comment by rngtng** [comment]
Ah got it: `ghcr.io/thim81/openapi-format`. Guess you need to map it to this repo so It shows up as `package` on the right

**Comment by thim81** [comment]
Hi @rngtng 

I m not really familiar with the docker publishing so if you have more tips, I m always happy to learn about them.

**Comment by rngtng** [comment]
@thim81 sure. Guess my PR is already a good start. Thanks the merge

**Pull request merged**
