### PR TITLE
Update defaultSort.json

### PR DESCRIPTION
**Pull request by shpoont**
Update `requestBody` according to the spec

### CODE REVIEW

**Comment by thim81** [comment]
Hi @shpoont,

Thanks for the PR. 
Would you mind sharing the spec where this is described so I can update the readme?

**Comment by shpoont** [comment]
Hi, this is according to https://spec.openapis.org/oas/v3.0.0#request-body-object

**Comment by thim81** [comment]
@shpoont Thanks again for taking the time to create the PR.

**Comment by thim81** [comment]
@shpoont just fyi: This will be part of the next release, if you would need this earlier you can pass along your custom sorting settings using the "--sortFile" CLI option.

**Comment by shpoont** [comment]
No worries, I am using `--sortFile` already :) 

Thanks!

**Pull request merged**
